version: "3.8"

services:
  app:
    build: .
    image: portfolio:latest
    container_name: myPortfolio
    ports:
      - "8000:8000"
    volumes:
      - /home/rleiva/data/portfolioMedia:/app/media
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    environment:
      - DEBUG=0

  # Will add postgreSQL db in the future
  db:
    image: postgres:latest
    container_name: portfolioDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - /home/rleiva/data/postgres:/var/lib/postgresql/data